# Name of database directory that is found in database/
db: "beerolama_v1"

# List of targets taa you wish filter out of your results
# (e.g. host species in metagenomic analysis)
filter_targets: 
 - Apis mellifera

# name of subdirectories of the data/ directory
# these can be used to keep samples separated into groups and maintain
# separation during all pipeline steps
# Leave blank (datapaths:) if there are no groups and all samples are
# found in data/
# A subdirectory of data/ can also be used to separate runs of the pipeline
datapaths: 
 - shallow
 - deep
