samples: 
 - shallow/shallow_AG-Ab-10_classification
 - shallow/shallow_AG-Ab-11_classification
 - shallow/shallow_AG-Ab-1_classification
 - shallow/shallow_AG-Ab-2_classification
 - shallow/shallow_AG-Ab-3_classification
 - shallow/shallow_AG-Ab-4_classification
 - shallow/shallow_AG-Ab-5_classification
 - shallow/shallow_AG-Ab-6_classification
 - shallow/shallow_AG-Ab-7_classification
 - shallow/shallow_AG-Ab-8_classification
 - shallow/shallow_AG-Ab-9_classification
 - shallow/shallow_AG-Bee-10_classification
 - shallow/shallow_AG-Bee-11_classification
 - shallow/shallow_AG-Bee-2_classification
 - shallow/shallow_AG-Bee-4_classification
 - shallow/shallow_AG-Bee-5_classification
 - shallow/shallow_AG-Bee-6_classification
 - shallow/shallow_AG-Bee-7_classification
 - shallow/shallow_AG-Bee-8_classification
 - shallow/shallow_AG-Bee-9_classification
 - shallow/shallow_AG-Gut-10_classification
 - shallow/shallow_AG-Gut-11_classification
 - shallow/shallow_AG-Gut-3_classification
 - shallow/shallow_AG-Gut-4_classification
 - shallow/shallow_AG-Gut-6_classification
 - shallow/shallow_AG-Gut-7_classification
 - shallow/shallow_AG-Gut-8_classification
 - shallow/shallow_AG-Gut-9_classification
 - shallow/shallow_AG-Hind-10_classification
 - shallow/shallow_AG-Hind-11_classification
 - shallow/shallow_AG-Hind-1_classification
 - shallow/shallow_AG-Hind-2_classification
 - shallow/shallow_AG-Hind-7_classification
 - deep/deep_AG-Ab-10_classification
 - deep/deep_AG-Ab-11_classification
 - deep/deep_AG-Ab-1_classification
 - deep/deep_AG-Ab-2_classification
 - deep/deep_AG-Ab-3_classification
 - deep/deep_AG-Ab-4_classification
 - deep/deep_AG-Ab-5_classification
 - deep/deep_AG-Ab-6_classification
 - deep/deep_AG-Ab-7_classification
 - deep/deep_AG-Ab-8_classification
 - deep/deep_AG-Ab-9_classification
 - deep/deep_AG-Bee-10_classification
 - deep/deep_AG-Bee-11_classification
 - deep/deep_AG-Bee-1_classification
 - deep/deep_AG-Bee-2_classification
 - deep/deep_AG-Bee-3_classification
 - deep/deep_AG-Bee-4_classification
 - deep/deep_AG-Bee-5_classification
 - deep/deep_AG-Bee-6_classification
 - deep/deep_AG-Bee-7_classification
 - deep/deep_AG-Bee-8_classification
 - deep/deep_AG-Bee-9_classification
 - deep/deep_AG-Gut-10_classification
 - deep/deep_AG-Gut-11_classification
 - deep/deep_AG-Gut-1_classification
 - deep/deep_AG-Gut-3_classification
 - deep/deep_AG-Gut-4_classification
 - deep/deep_AG-Gut-5_classification
 - deep/deep_AG-Gut-6_classification
 - deep/deep_AG-Gut-7_classification
 - deep/deep_AG-Gut-8_classification
 - deep/deep_AG-Gut-9_classification
 - deep/deep_AG-Hind-10_classification
 - deep/deep_AG-Hind-11_classification
 - deep/deep_AG-Hind-1_classification
 - deep/deep_AG-Hind-2_classification
 - deep/deep_AG-Hind-3_classification
 - deep/deep_AG-Hind-7_classification
