configfile: "config.yaml"
SAMPLES=config["samples"]
DB=config["database"]

rule all:
	input:
		expand("rarefied/{sample}.csv", sample=SAMPLES)

# filter out reads that are host (A. mellifera), or unclassified
rule filter:
	input:
		"{sample}.txt"
	output:
		"filtered/{sample}_filtered.txt"
	shell:
		"cat {input} | grep -v \"Apis mellifera\|unclassified\" > {output}"

rule get_db_inspection:
    input:
        DB
    output:
        "db_inspection.txt"
    shell:
        "kraken2-inspect --db {input} > db_inspection.txt"

# TODO: translation must be done with custom script
rule translate:
	input:
		db_inspection = "db_inspection.txt"
		readfiles = expand("filtered/{sample}_filtered.txt", sample=config["samples"])
	output:
		"translated/{sample}.txt"
	shell:
		"scripts/kraken2-translate.py"

rule krakefaction:
	input:
		trans="translated/{sample}.txt",
		untrans="{sample}.txt"
	output:
		"rarefied/{sample}.csv"
	shell:
		"krakefaction -u {input.untrans} -t {input.trans} -o {output}"
